### ISSUE TITLE
not an issue, but a question

### ISSUE THREAD

**Issue by chrishsr** [Wanderson-Magalhaes/Simple_PySide_Base#1]
how did you delete the standart "minimize, full size and close" buttons and change them with yours?

**Comment by Wanderson-Magalhaes** [comment]
You do not need to delete, just hide these widgets.
Use: self.ui.btn_maximize_restore.hide() and self.ui.btn_minimize.hide() to hide in the Main.py.
Another option is to create a function in the ui_functions.py file to hide the buttons you want.
![pRINT](https://user-images.githubusercontent.com/60605512/84679772-18451080-af08-11ea-86cb-4505aa9aced7.PNG)

**Comment by Sienkowski99** [comment]
But how did u remove default windows border with all the stuff
