### ISSUE TITLE
Not Really an issue

### ISSUE THREAD

**Issue by HuskyCodez** [Wanderson-Magalhaes/Simple_PySide_Base#11]
so i was wondering how i would be able to add text to a new custom menu, help would be appreciated thanks

**Comment by Wanderson-Magalhaes** [comment]
In the README have this print, is very easy. 
File: **main.py**

![94625100-56372c00-028e-11eb-978e-22165d8f77c8](https://user-images.githubusercontent.com/60605512/98263272-644f2b00-1f65-11eb-9eba-cbf28773b7bc.png)

**Comment by HuskyCodez** [comment]
> In the README have this print, is very easy.
> File: **main.py**
> 
> ![94625100-56372c00-028e-11eb-978e-22165d8f77c8](https://user-images.githubusercontent.com/60605512/98263272-644f2b00-1f65-11eb-9eba-cbf28773b7bc.png)

thanks for the prompt response!
