### ISSUE TITLE
QWebEngineView unresponsive

### ISSUE THREAD

**Issue by deirdrebridges** [Wanderson-Magalhaes/Simple_PySide_Base#12]
Embedded QWebEngineView widget is laggy and unresponsive, as in does not respond to anything unless I click somewhere else on the screen. For example, I embedded a QWebEngineView widget in the home page using this code:
self.browser = QWebEngineView()
self.ui.verticalLayout_10.addWidget(self.browser)
self.browser.load(QUrl("http://www.google.com"))
self.show()
The embedded widget will remain blank unless I click somewhere else for example my code editor. Then when google shows up you are not able to see what you type in until you click somewhere else on the screen.
It works totally fine if it is not embedded (achieved through not adding the widget to the layout)
This is a great project, thank you so much!

**Comment by Wanderson-Magalhaes** [comment]
QWebEngine is not part of this project, it could be an implementation error you are making.
Try veriricar on the official website qt.io

**Comment by pArtheum** [comment]
Hi QWebEngineView has an issue in QT regarding event handling. You have to put an eventFilter on a child of QWebEngineView instead.

**Comment by nekooee** [comment]
> Hi QWebEngineView has an issue in QT regarding event handling. You have to put an eventFilter on a child of QWebEngineView instead.

I have the same problem that only happens with this Template. There is no problem without using this template. When I use QWebEngineView, changes are not displayed, not even text selection! Until I change the window's size... but when I display it in an independent window with a title bar and do not use this template, there is no problem.
I did not understand your solution! I will get the events and then what should I do??

> QWebEngine is not part of this project, it could be an implementation error you are making. Try veriricar on the official website qt.io

Unfortunately, this problem occurs only by using this Template. I don't know how to solve it

**Comment by nekooee** [comment]
> Embedded QWebEngineView widget is laggy and unresponsive, as in does not respond to anything unless I click somewhere else on the screen. For example, I embedded a QWebEngineView widget in the home page using this code: self.browser = QWebEngineView() self.ui.verticalLayout_10.addWidget(self.browser) self.browser.load(QUrl("http://www.google.com")) self.show() The embedded widget will remain blank unless I click somewhere else for example my code editor. Then when google shows up you are not able to see what you type in until you click somewhere else on the screen. It works totally fine if it is not embedded (achieved through not adding the widget to the layout) This is a great project, thank you so much!

Please tell me what you did if you could solve the problem so far. I need a solution.
