### ISSUE TITLE
Contact details

### ISSUE THREAD

**Issue by allanleal** [Wanderson-Magalhaes/Simple_PySide_Base#14]
Hi Wanderson. Amazing work! I'm a big fan of Qt as well. Please add some form of contact so that people can reach you in private (my case for example!). Abraços, Allan (allan.leal at erdw.ethz.ch)

**Comment by Wanderson-Magalhaes** [comment]
Have Discord: https://discord.gg/WufW3ZHZyX​

**Comment by allanleal** [comment]
The link above is not recognised in discord. If you have Gitter, contact me on https://gitter.im/allanleal

**Comment by Wanderson-Magalhaes** [comment]
New link: https://discord.gg/6GdeQAWggC
