### ISSUE TITLE
Is there a mac version for this app?

### ISSUE THREAD

**Issue by AmeyVijeesh** [Wanderson-Magalhaes/Simple_PySide_Base#19]
This code, when executed in Windows, works properly. However, when opened in Mac, the app is not responding, and not visible when executed. 

So, do you have a **Mac** version of this app that runs properly?

**Comment by 0x30c4** [comment]
Did you tried to change the path separator from \ to / ?

**Comment by AmeyVijeesh** [comment]
Yes, but it didn't work.
