### ISSUE TITLE
Updating QT Designer files does not affect actual App

### ISSUE THREAD

**Issue by techboycr** [Wanderson-Magalhaes/Simple_PySide_Base#6]
Hello!

Thank you so much for this project great starter for a project.

I am just wondering if you use another tool to convert the QT Designer file to python and do we update the design.

Thank you so much for your time.

**Comment by Wanderson-Magalhaes** [comment]
Hi Abraham,
To convert to Python I use the Qt Designer (PySide2 version). When installing PySide2 it is also install Qt Designer with the option to export in Python.
![image](https://user-images.githubusercontent.com/60605512/92296306-b514ba00-ef09-11ea-9c22-f019f3a1afdd.png)

To convert the resource files I use the command line "pyside-rcc -o resource_rc.py resource.qrc"
