### ISSUE TITLE
Glitch ao diminuir tamanho da tela 

### ISSUE THREAD

**Issue by demelomatt** [Wanderson-Magalhaes/Simple_PySide_Base#7]
Olá, Wanderson.
Toda vez ao diminuir o tamanho da tela e estando algum widget presente na página, a interface pisca.
Isso ocorre por exemplo na página "Custom Widgets".
Verifiquei que é algo relacionado ao Toggle Burguer Menu. Desativando essa funcionalidade e deixando o menu estático, o problema desaparece.
Você tem alguma ideia de alguma solução para esse problema?

(Perdão por postar em português, mas meu inglês é bem básico).

**Comment by Wanderson-Magalhaes** [comment]
Então mano, aqui eu não tive esse problema. Veja se todos os Widgets estão preparados para serem responsivos, caso algum esteja maior que o frame pai pode quebrar sim o Layout, verifique os valores maximo e minimo se estão tudo ok.
Tente ver se é algum desses o problema.
