### ISSUE TITLE
Buttons don't click until menu bar is open in PySide2

### ISSUE THREAD

**Issue by Josh596** [Wanderson-Magalhaes/Simple_PySide_Base#8]

**Comment by Josh596** [comment]
I love your work. It's a very unique design

**Comment by Wanderson-Magalhaes** [comment]
Here mouse clicks work correctly on all buttons, are you creating your menus as in the example below?

![add-MENUS](https://user-images.githubusercontent.com/60605512/94624948-ff315700-028d-11eb-8e62-152d12fa6006.png)

**Comment by Josh596** [comment]
Try it with Pyside2, the menu bar had to be max length before the button click showed any effect. It worked perfectly on PyQt5

**Comment by Josh596** [comment]
Thank you for your work

**Comment by Jaccxc** [comment]
I got the same problem here. The clickable area of the button is somehow reduced because of the button style sheet(padding and border). The bar must be extended to click the button. How do I solve this?

![圖片](https://user-images.githubusercontent.com/71752872/94665528-d87f2900-033e-11eb-9eb0-6d3a8ce78cb9.png)
![圖片](https://user-images.githubusercontent.com/71752872/94665532-da48ec80-033e-11eb-8f83-42c1aa7fd7d3.png)

**Comment by Wanderson-Magalhaes** [comment]
Guys, I found the problem and it is caused by the latest version of **PySide2 (5.15.1)**, in version "**5.14.2**" it works perfectly. **I will see as soon as possible why I am causing this problem**.
Try to install version 5.14.2 and you will see that it is working correctly on it.

**Comment by Wanderson-Magalhaes** [comment]
Guys, I found the problem and it is caused by the latest version of **PySide2** (5.15.1), in version "**5.14.2**" it works perfectly. **I will see as soon as possible why I am causing this problem**.
Try to install version 5.14.2 and you will see that it is working correctly on it.

**Comment by Wanderson-Magalhaes** [comment]
@Jaccxc and @Josh596
**It seems to be a Bug from PySide2 version 5.15.0 and 5.15.1 and also from PyQt5. Use version "5.14.2.2" for this project (pip install pyside2 == 5.14.2.2)**
**Note**: https://wiki.qt.io/Qt_for_Python_Development_Notes
**In October they will release version 6 of Qt**, we will wait for them to solve these problems or bring some solution for the same.
Another project with de same problem:
https://github.com/napari/napari/issues/1312

**Comment by Josh596** [comment]
Thank you so much, It works in PySide2 version 5.14.2.2(Just as you said)
